---
title: "My First Flipbook"
subtitle: "With flipbookr and xaringan"
author: "Ted Laderas"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include = FALSE}
library(flipbookr)
library(tidyverse)
knitr::opts_chunk$set(fig.width = 6, message = FALSE, 
                      warning = FALSE, comment = "", 
                      cache = F)
library(palmerpenguins)
data("penguins")
```


```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}
@media print {
  .has-continuation {
    display: block;
  }
}
```

```{r my_penguins, include = FALSE}
penguins %>% 
  ggplot() +
  aes(x=bill_length_mm) +
  aes(y=bill_depth_mm) +
  geom_point() +
  aes(color = species) +
  scale_color_manual(values = 
      c("darkorange","purple","cyan4")) +
  facet_wrap(~island) +
  theme_minimal() +
  labs(x="Bill Length (mm)", 
       y="Bill Depth (mm)", 
       title = "Palmer Penguins by Islands") 
  
```

---

`r chunk_reveal(chunk_name = "my_penguins", title = "### Faceting the Palmer Penguins!")`